Repository shalb/cluster.dev, pull requests merged in 2020-10, with the labels that each got.

#92 [v0.3.3] Document release creation and fix docs
  .github/workflows/aws.yml
  .github/workflows/digitalocean.yml
  .vscode/settings.json
  README.md
  action.yml
  docs/CONTRIBUTING.md
  docs/ROADMAP.md
  docs/add-new-docs.md
  docs/add-provider-provisioner.md
  docs/getting-started-aws.md
  docs/getting-started-digitalocean.md
  docs/git-provider-support.md
  docs/release-new-version.md
  docs/style-guide.md
  mkdocs.yml
Labels: kind/documentation

#70 Cli installer 3rd iteration
  .gitignore
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  docs/aws-iam-permissions.md
  docs/getting-started-aws.md
  install/aws_logs_parser.py
  install/installer/Dockerfile
  install/installer/README.md
  install/installer/aws.py
  install/installer/aws_config.py
  install/installer/aws_policy.json
  install/installer/cluster_dev.py
  install/installer/docker-compose.yaml
  install/installer/entrypoint.sh
  install/installer/github.py
  install/installer/logger.py
  install/installer/requirements-dev.in
  install/installer/requirements-dev.txt
  install/installer/requirements.in
  install/installer/requirements.txt
  install/installer/test_installer.py
  install/installer/validate.py
  install/installer_aws_install_req_permissions.json
Labels: area/CLI installer, kind/feature

#96 Fix docs style and document undocumented
  .gitignore
  .vscode/settings.json
  docs/OPTIONS.md
  docs/getting-started-aws.md
  docs/getting-started-digitalocean.md
  docs/run-reconciler-locally.md
  mkdocs.yml
  pkg/provider/aws/module/addons/addons.go
Labels: kind/documentation

#95 Document behaviour in code
  .cluster.dev/aws-eks-minimum-conf.yaml
  .cluster.dev/aws-eks.yaml
  .cluster.dev/aws-minikube-minimum-conf.yaml
  .cluster.dev/aws-minikube.yaml
  .cluster.dev/digitalocean-k8s-minimum-conf.yaml
  .cluster.dev/digitalocean-k8s.yaml
Labels: kind/documentation

#97 Update pre-commit hooks
  .github/workflows/pre-commit-main.yaml
  .github/workflows/pre-commit-pr.yaml
  .pre-commit-config.yaml
Labels: area/CI/github actions
